// Generated from the curriculum catalogue; verified by timetableSubjects.test.js.
export const VALID_TIMETABLE_SUBJECTS = [
  "English Elective",
  "English Core",
  "Hindi Elective",
  "Hindi Core",
  "Urdu Elective",
  "Urdu Core",
  "Sanskrit Elective",
  "Sanskrit Core",
  "Punjabi",
  "Bengali",
  "Tamil",
  "Telugu (AP)",
  "Telugu (Telangana)",
  "Sindhi",
  "Marathi",
  "Gujarati",
  "Manipuri",
  "Malayalam",
  "Odia",
  "Assamese",
  "Kannada",
  "Arabic",
  "Tibetan",
  "French",
  "German",
  "Russian",
  "Persian",
  "Nepali",
  "Limboo",
  "Lepcha",
  "Bhoti",
  "Kokborok",
  "Bodo",
  "Tangkhul",
  "Japanese",
  "Bhutia",
  "Spanish",
  "Kashmiri",
  "Mizo",
  "History",
  "Political Science",
  "Geography",
  "Economics",
  "Carnatic Music (Vocal)",
  "Carnatic Music (Melodic Instruments)",
  "Carnatic Music (Percussion Instruments - Mridangam)",
  "Hindustani Music (Vocal)",
  "Hindustani Music (Melodic Instruments)",
  "Hindustani Music (Percussion Instruments)",
  "Psychology",
  "Sociology",
  "Mathematics",
  "Applied Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biotechnology",
  "Engineering Graphics",
  "Physical Education",
  "Painting",
  "Graphics",
  "Sculpture",
  "Applied/Commercial Art",
  "Business Studies",
  "Accountancy",
  "Kathak Dance",
  "Bharatanatyam Dance",
  "Kuchipudi Dance",
  "Odissi Dance",
  "Manipuri Dance",
  "Kathakali Dance",
  "Home Science",
  "Informatics Practices",
  "Computer Science",
  "Entrepreneurship",
  "Knowledge Tradition and Practices of India",
  "Legal Studies",
  "NCC",
  "Retail",
  "Information Technology",
  "Web Application",
  "Automotive",
  "Financial Markets Management",
  "Tourism",
  "Beauty and Wellness",
  "Agriculture",
  "Food Production",
  "Front Office Operations",
  "Banking",
  "Marketing",
  "Health Care",
  "Insurance",
  "Horticulture",
  "Typography and Computer Application",
  "Geospatial Technology",
  "Electrical Technology",
  "Electronic Technology",
  "Multi-Media",
  "Taxation",
  "Cost Accounting",
  "Office Procedures and Practices",
  "Shorthand (English)",
  "Shorthand (Hindi)",
  "Air-Conditioning and Refrigeration",
  "Medical Diagnostics",
  "Textile Design",
  "Design",
  "Salesmanship",
  "Business Administration",
  "Food Nutrition and Dietetics",
  "Mass Media Studies",
  "Library and Information Science",
  "Fashion Studies",
  "Yoga",
  "Early Childhood Care and Education",
  "Artificial Intelligence",
  "Data Science",
  "Physical Activity Trainer",
  "Land Transportation Associate",
  "Electronics and Hardware",
  "Design Thinking and Innovation"
]
